name: example_hello_wasm_cpp_flutter
description: An example project with WASM, C++ and Flutter.
publish_to: 'none'
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  js: ^0.6.3
  flutter:
    sdk: flutter